chipset = "msm8953"

[bootimg]
base = 0x70000000
kernel = 0x8000
ramdisk = 0x1000000
second = 0
tags = 0x100
pagesize = 2048

[[device]]
vendor = "asus"
model = "ze520kl"
append = "console=ttyMSM0,115200 firmware_class.path=/usr/lib/firmware/zenfone3"

[[device]]
vendor = "asus"
model = "ze552kl"
append = "console=ttyMSM0,115200 firmware_class.path=/usr/lib/firmware/zenfone3"
