#!/bin/sh

set -e

# This file contains the list of all packages from the latest testing netinst image
CURRENT_LIST="https://cdimage.debian.org/cdimage/daily-builds/daily/current/amd64/list-cd/debian-testing-amd64-netinst.list.gz"

# Firmware packages contain either "firmware" or "microcode" in their name
# (ref: https://salsa.debian.org/images-team/debian-cd/-/blob/master/tools/generate_firmware_task#L8)
FW_LIST="$(curl $CURRENT_LIST 2>/dev/null | zcat | grep -E 'firmware|microcode' | sort)"

for fw in $FW_LIST; do
    # Entries are .deb filenames so far, extract the package name
    fwname="$(echo $fw | cut -d '_' -f1)"
    # Output entry properly formatted for direct copy/pasting
    echo "      - $fwname"
done
